version: '3.9'
services:
  wallet_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/wallet-backend/src
      - ./test:/wallet-backend/test
      - ./package.json:/wallet-backend/package.json
    command: ./wait-for-it.sh wallet_test_db:5432 -- bash -c "npm run lint && npm run testsOnDocker"
    depends_on:
      - wallet_test_db
    profiles: ['startTests']

  wallet_test_db:
    image: postgres:15.1
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    environment:
      PGUSER: wallet_db
      PGPASSWORD: wallet_password
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "9002:5432"

