version: '3.9'
services:
  wallet_test_db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    environment:
      PGUSER: wallet_db
      PGPASSWORD: wallet_password
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "9002:5432"

