name: Run tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: run tests
        run: docker-compose -f docker-compose.test.yml --profile startTests up --exit-code-from wallet_test
